- name: 在远程服务器上构建 Docker 镜像
  hosts: "{{ target_host }}"
  tasks:
    - name: 进入项目根目录
      ansible.builtin.shell:
        cmd: "cd {{ dest_path }} && docker build -t devops-api:v1 ."
      register: build_result
      failed_when: build_result.rc != 0  # 如果构建失败则中止
    - name: 显示构建结果
      ansible.builtin.debug:
        msg: >
          Docker 镜像构建成功:
          - 状态码: {{ build_result.rc }}
          - 项目路径: {{ dest_path }}