captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 1
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: error
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
email:
    to: ""
    from: ""
    host: ""
    secret: ""
    nickname: ""
    port: 0
    is-ssl: false
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: ""
    bucket: ""
    endpoint: ""
    access-key: ""
    secret-key: ""
jwt:
    signing-key: 6fde2c9e-54d6-45e1-9ed9-3cb684f8da9e
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 0
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts: []
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: cg_devops
    username: root
    password: Devops%8
    path: 192.168.217.134
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
zap:
    level: info
    prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true
elasticsearch:
  enable: true
  url: http://192.168.217.142:9200 #http://10.10.182.220:9200
  sniff: false  #将返回的url 作为请求的路径
  healthcheckInterval: 5s
  index-prefix: gva
jenkins:
  url: http://119.8.127.96:8001/
  user: admin
  api-token: 11d2d3cd4784aa28379905bf13988ad50e
telegram:
  url: https://api.telegram.org/bot
  bot-token: 7449933946:AAGSpUHIsi9cTgc65O9CFheOia3czrLS8l4 #@CG33333_bot 机器人
  chat-id: -4275796428 #测试群组 -4275796428   #CG游戏更新发布群 -1001534909056 #未使用
  webhook-url: https://e692-91-75-118-214.ngrok-free.app/jenkins/telegram-webhook
  webhook-port: 5299  #开发环境使用
cloudflare:
  cf-api-login: djpt36@163.com
  global-key: 0237bd44ec3b541e622d6aa1b187aac9193f0
  api-url: https://api.cloudflare.com/client/v4/zones