captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 1
    open-captcha-timeout: 3600
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: error
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
email:
    to: ""
    from: ""
    host: ""
    secret: ""
    nickname: ""
    port: 0
    is-ssl: false
excel:
    dir: ./resource/excel/
hua-wei-obs:
    path: ""
    bucket: ""
    endpoint: ""
    access-key: ""
    secret-key: ""
jwt:
    signing-key: 6fde2c9e-54d6-45e1-9ed9-3cb684f8da9e
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mongo:
    coll: ""
    options: ""
    database: ""
    username: ""
    password: ""
    auth-source: ""
    min-pool-size: 0
    max-pool-size: 0
    socket-timeout-ms: 0
    connect-timeout-ms: 0
    is-zap: false
    hosts: []
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: cg_devops
    username: root
    password: Devops%588
    path: localhost
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
zap:
    level: info
    prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    max-age: 0
    show-line: true
    log-in-console: true
elasticsearch:
  enable: true
  url: http://localhost:9200 #http://10.10.182.220:9200
  sniff: false  #将返回的url 作为请求的路径
  healthcheckInterval: 5s
  index-prefix: gva
jenkins:
  url: k7kesncx4XfeFZY4UUfR+CZwEyXXW3LezEQ= #http://jenkins1.3333d.vip/  #加密
  user: mqkHqyM= #admin   # 加密
  api-token: yvxf8H0srC3aTM81XlCE4jJrh+X8zzrpSVvk4+tvKJk8nA== # 115202b0a72dadd4f89878e7d352aa8552
  testUrl: k7kesj4k4TLRHpM6VlqT+JRZNNgp4+4ksYlJTNQ=     #测试环境  加密 https://jenkins.qiyinyun.com/
  testUser: iaIFtg==   # 加密 root
  testToken: yvxd8n17qyyMGZhiCQbRsny4xjGTbnbkWflX48pqz3q/SA==    # 加密 11700ee17be3621da8bb4443e073763a69
telegram:
  url: https://api.telegram.org/bot
  bot-name: u44t8X4t/S7kGZIl    # 加密后的 机器人用户名 '@CG33333_bot'
  #bot-name: u44t+nUm9ijkGZIl     #加密后的 机器人用户名 @CG88885_bot
  bot-token: zPle+3Qt/SSPTccQfnOzpjlhztU7WohodQ8hDikpQlvmPjyH1ExkIDIC28D7gQ== # 加密后的 CG33333_Bot token 7449933946:AAGSpUHIsi9cTgc65O9CFheOia3czrLS8l4
  #bot-token: zPlZ+n8q/CSCTccQfnKXkXhBV6fRnm6K8wQ2DDvZhoM6SBXDL2g8WVwu6II2cg==  # 加密后的@CG88885 bot-token    7438242996:AAFwGnP8mQBmvcjiDggltiiOTMo14XeOoT4
  aes-key: 61afa6ddca1285f640b03c8c64d02c31
  chat-id:  #测试群组 -4275796428
  webhook-url: k7kesj4k4TLaQs1lEgbR4deTc9rgR/A+U2QZjEKki6pGtgjzzJqbtAdg+0mfyrvpUwqIEc3lPQteAMB/xNqjNEhx  # 加密后的 ngrok url
  #webhook-url: k7kesj4k4TKJSshnEgzN5H50H3XVlDNSUZ7kPVi0/zreOLhPMaPkopMyTdU482t/I7Z2BZ5t5F7yk3K9124TaYc= # 线上加密后 ngrok URL
  authorized_users:
    - David5886
    - grass9966
    - nikon_aaa
    - tank9873
    - pitter88
    - Jos2099
cloudflare:
  cf-api-login: djpt36@163.com
  global-key: 0237bd44ec3b541e622d6aa1b187aac9193f0
  api-url: https://api.cloudflare.com/client/v4/zones
