services:
  devops-api:
    image: centos:7
    working_dir: /opt
    container_name: devops-api    #自定义
    command: "./devops-api -c config.yaml"
    network_mode: "host"      # 共享宿主机网络配置 容器中程序可访问其他容器端口服务
    ports:
      - "5888:5888"      #
    volumes:
      - ./:/opt
    environment:
      - TZ=Asia/Shanghai
# Kompose 转换 docker-compose 文件为k8s 资源 部署文件   默认版本为3